server:
  port: 8999

spring:
  application:
    name: foo-payment-api
  messages:
    basename: config.i18n.messages
  flyway:
    enabled: false
    open-in-view: false

logging:
  level:
    com:
      cesarsol:
        foopaymentapi: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: FULL

  banner:
    location: classpath:static/banner.txt
  cloud:
    loadbalancer:
      ribbon:
        enabled: false