spring:
  datasource:
    url: jdbc:postgresql://foo-database:5432/foo-db?currentSchema=public
    username: foo-user-app
    password: f00-P@ss
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

springdoc:
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html
    api-docs:
      enabled: true

integration:
  product-sale-service:
    url: http://foo-wiremock:8080/product-sales
  parameter-api:
    url: http://foo-wiremock:8080/parameter-api