version: "3.9"
services:
  foo-payment-api:
    container_name: foo-payment-api
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    build: ../
    ports:
      - 8999:8999
  foo-database:
    container_name: foo-database
    image: postgres:14.1
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=foo-user-app
      - POSTGRES_PASSWORD=f00-P@ss
      - POSTGRES_DB=foo-db
  flyway:
    container_name: foo-flyway
    image: flyway/flyway:9.2.3
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ../src/main/resources/db/migrations:/flyway/sql
      - ./database/flyway.config:/flyway/conf/flyway.config
    depends_on:
      - foo-database

  foo-wiremock:
    container_name: foo-wiremock
    image: wiremock/wiremock:2.34.0
    command: --verbose
    volumes:
      - ../src/test/resources/stubs:/home/wiremock
    ports:
      - 8090:8080